### ISSUE TITLE
link to 'javascript' page is broken.

### ISSUE THREAD

**Issue by semtle** [Monogatari/Documentation#1]
Could you check it?

**Comment by Hyuchia** [comment]
You are right! Sorry about that, I'll check it right away, on the mean time, you can read the contents here: https://github.com/Monogatari/Documentation/blob/master/script/javascript.md

Thanks a lot for reporting it!

**Comment by Hyuchia** [comment]
Hi! The issue has been fixed, you should now be able to access it normally :+1:

Again, thanks a lot for reporting it!
