### ISSUE TITLE
Broken link for `add scene`

### ISSUE THREAD

**Issue by AppLoidx** [Monogatari/Documentation#12]
Link for a `add scene` is broken in documentation

[step-4-make-your-first-visual-novel.md](https://github.com/Monogatari/Documentation/blob/develop/getting-started/step-4-make-your-first-visual-novel.md)

Point 7, page is not found. He refers to https://developers.monogatari.io/documentation/script/scenes/

**Comment by LoganTann** [comment]
Fixed in a8abf6d.

@Hyuchia This issue should be closed
